#!/usr/bin/env python3
"""Generate src/unicode_tables.h: the character classes and NFC data q27's
tokenizer needs for byte-exact parity with the Qwen3.6/3.8 HF tokenizer.

Everything is derived from the REFERENCE implementation (the `tokenizers`
library, the same Rust code transformers runs), not from Python's
unicodedata, because the two disagree at the edges (e.g. Oniguruma's \\s does
not include U+001C-U+001F, Python's isspace does):

- pre-tokenizer classes, by probing the checkpoint's own Split pre-tokenizer
  with "a" + c + c + "a" for every scalar value c:
    1 piece                -> LM (\\p{L} or \\p{M}: joins the letter run)
    4 pieces               -> N  (\\p{N}: one piece per digit)
    [a, c, ca]             -> S  (\\s: a whitespace run, then prefix + letters)
    [a, cc, a]             -> O  (anything else: the punctuation branch)
  CR and LF are special-cased by the regex and handled in code.
- NFC: full canonical decompositions from tokenizers' NFD normalizer;
  primary composites = pairs (a, b) with NFD(c) == a+b and NFC(a+b) == c
  under tokenizers' NFC; canonical combining classes from unicodedata,
  cross-checked by the round trip at the end.

usage: gen_unicode_tables.py <tokenizer.json> <out.h>"""
import sys, unicodedata
from tokenizers import Tokenizer, normalizers

tok_json, out_path = sys.argv[1:3]
pt = Tokenizer.from_file(tok_json).pre_tokenizer
nfd, nfc = normalizers.NFD(), normalizers.NFC()

def scalars():
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF: continue
        yield cp

def probe_class(c):
    offs = [o for _, o in pt.pre_tokenize_str("a" + c + c + "a")]
    if len(offs) == 1: return "LM"
    if len(offs) == 4: return "N"
    if len(offs) == 3: return "S" if offs[1][1] - offs[1][0] == 1 else "O"
    return "?"

classes = {"LM": [], "N": [], "S": []}
odd = []
for cp in scalars():
    if cp in (0x0A, 0x0D): continue
    k = probe_class(chr(cp))
    if k in classes: classes[k].append(cp)
    elif k == "?": odd.append(cp)
if odd: sys.exit(f"unclassifiable code points: {[hex(c) for c in odd[:20]]}")

def ranges(cps):
    out = []
    for cp in cps:
        if out and out[-1][1] == cp - 1: out[-1][1] = cp
        else: out.append([cp, cp])
    return out

# NFC data
decomp = {}
for cp in scalars():
    c = chr(cp)
    d = nfd.normalize_str(c)
    if d != c: decomp[cp] = [ord(x) for x in d]
ccc = {cp: unicodedata.combining(chr(cp)) for cp in scalars() if unicodedata.combining(chr(cp))}
comp = {}
for cp, d in decomp.items():
    # primary composite: NFC maps (NFC(prefix), last) back to it. The prefix
    # is composed first so multi-level ones (U+1E08 = C-cedilla + acute)
    # land on their real one-level pair.
    if len(d) < 2: continue
    first = nfc.normalize_str("".join(chr(x) for x in d[:-1]))
    if len(first) == 1 and nfc.normalize_str(first + chr(d[-1])) == chr(cp):
        comp[(ord(first), d[-1])] = cp
# Hangul is algorithmic in the C++ (as in every NFC implementation); drop it
# from the tables
HS, HE = 0xAC00, 0xAC00 + 11172
decomp = {k: v for k, v in decomp.items() if not HS <= k < HE}
comp = {k: v for k, v in comp.items() if not HS <= v < HE}

def ccc_ranges():
    out = []
    for cp in sorted(ccc):
        if out and out[-1][1] == cp - 1 and out[-1][2] == ccc[cp]: out[-1][1] = cp
        else: out.append([cp, cp, ccc[cp]])
    return out

flat, index = [], []
for cp in sorted(decomp):
    index.append((cp, len(flat), len(decomp[cp]))); flat += decomp[cp]

L = []
L.append("// GENERATED by tools/gen_unicode_tables.py from the checkpoint's tokenizer.json")
L.append(f"// (tokenizers library pre-tokenizer + NFD/NFC normalizers; unicodedata "
         f"{unicodedata.unidata_version} for combining classes). Do not edit by hand.")
L.append("#pragma once\n#include <cstdint>\n\nnamespace q27 { namespace unicode {\n")
L.append("struct Range { uint32_t lo, hi; };")
L.append("struct CccRange { uint32_t lo, hi; uint8_t ccc; };")
L.append("struct Decomp { uint32_t cp; uint16_t off; uint8_t len; };")
L.append("struct Comp { uint64_t pair; uint32_t cp; };  // pair = (first << 21) | second\n")
for name, key in (("kLetterMark", "LM"), ("kNumber", "N"), ("kSpace", "S")):
    rs = ranges(classes[key])
    L.append(f"// {key}: {len(classes[key])} code points in {len(rs)} ranges")
    L.append(f"static const Range {name}[] = {{")
    L += [f"    {{0x{a:X}, 0x{b:X}}}," for a, b in rs]
    L.append("};")
L.append(f"static const CccRange kCcc[] = {{")
L += [f"    {{0x{a:X}, 0x{b:X}, {c}}}," for a, b, c in ccc_ranges()]
L.append("};")
L.append(f"static const uint32_t kDecompFlat[] = {{")
for i in range(0, len(flat), 12): L.append("    " + ", ".join(f"0x{x:X}" for x in flat[i:i + 12]) + ",")
L.append("};")
L.append(f"static const Decomp kDecomp[] = {{")
L += [f"    {{0x{cp:X}, {off}, {n}}}," for cp, off, n in index]
L.append("};")
L.append(f"static const Comp kComp[] = {{")
L += [f"    {{0x{(a << 21) | b:X}ull, 0x{c:X}}}," for (a, b), c in sorted(comp.items(), key=lambda kv: (kv[0][0] << 21) | kv[0][1])]
L.append("};")
L.append("\n}}  // namespace q27::unicode")
open(out_path, "w").write("\n".join(L) + "\n")
print(f"{out_path}: LM {len(classes['LM'])} cps/{len(ranges(classes['LM']))} ranges, "
      f"N {len(classes['N'])}/{len(ranges(classes['N']))}, S {len(classes['S'])}/{len(ranges(classes['S']))}, "
      f"ccc {len(ccc)}, decomp {len(decomp)} ({len(flat)} cps), comp {len(comp)}")
# where the reference and unicodedata disagree, for the record
gc = lambda cp: unicodedata.category(chr(cp))
lm_ud = {cp for cp in scalars() if gc(cp)[0] in "LM"} - {0x0A, 0x0D}
print("LM vs unicodedata L|M: only-reference", len(set(classes["LM"]) - lm_ud), "only-unicodedata", len(lm_ud - set(classes["LM"])))
n_ud = {cp for cp in scalars() if gc(cp)[0] == "N"}
print("N  vs unicodedata N:   only-reference", len(set(classes["N"]) - n_ud), "only-unicodedata", len(n_ud - set(classes["N"])))
s_py = {cp for cp in scalars() if chr(cp).isspace()} - {0x0A, 0x0D}
print("S  vs Python isspace:  only-reference", sorted(hex(c) for c in set(classes["S"]) - s_py),
      "only-isspace", sorted(hex(c) for c in s_py - set(classes["S"])))
